//package com.example.mycontainer;
//
///**
// * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY StartUp. */
//public class StartUp$$CrashProtocolImpl extends AbProtocolFactory<ICrashProtocol> {
//    @NonNull
//    @Override
//    public ICrashProtocol createProtocol(Context context, boolean isDebug) {
//        ICrashProtocol icrashprotocol = new CrashProtocolImpl();
//        icrashprotocol.onCreate(context,isDebug);
//        return icrashprotocol;
//    }
//
//    @NonNull
//    @Override
//    public Class<ICrashProtocol> getProtocol() {
//        return ICrashProtocol.class;
//    }
//}
