package com.zs.mpaas.startup.compiler.utils;

/**
 * ******************************
 * 项目名称:JDCompilerMoudle
 *
 * @Author zhangsen
 * 邮箱:zhangsen839705693@163.com
 * 创建时间:2021    1:51 下午
 * 说明:
 * ******************************
 */
public class Consts {
    public static final String PACKAGE_OF_GENERATE_FILE = "com.zs.npm.impl.compiler.startup";
    public static final String Annotation_MethodCreateProtocol = "createProtocol";
    public static final String Annotation_MethodGetProtocol = "getProtocol";
    public static final String Annotation_NON = ",";



    public static final String Protocol_MethodName = "onCreate";
    public static final String KEY_MODULE_NAME = "AROUTER_MODULE_NAME";


    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY JDStartUp.";
    public static final String IROUTE_GROUP = "com.example.baseprotocol";
    public static final String IROUTE_GROUP_CLASSNAME = "AbProtocolFactory";

}
